import React, { Component } from 'react'

export default class HotspotsPage extends Component {
  render() {
    return (
      <div class="ui cards">
          <div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/steve.jpg" class="ui mini right floated image"/><div class="header">Spur Tree</div>
            <div class="ui star rating" role="radiogroup" tabindex="-1"><i tabindex="0" aria-checked="false" aria-posinset="1" aria-setsize="4" class="active icon" role="radio"></i><i tabindex="0" aria-checked="false" aria-posinset="2" aria-setsize="4" class="active icon" role="radio"></i><i tabindex="0" aria-checked="true" aria-posinset="3" aria-setsize="4" class="active icon" role="radio"></i><i tabindex="0" aria-checked="false" aria-posinset="4" aria-setsize="4" class="icon" role="radio"></i></div>
          <div class="meta">Friends who have been there</div><div class="description">Hottest restaurant in town <strong>best friends</strong></div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div><div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/molly.png" class="ui mini right floated image"/><div class="header">Untamed</div><div class="meta">Friends have been there</div><div class="description">This is a great spot for night life <strong>musicians</strong></div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div><div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/jenny.jpg" class="ui mini right floated image"/><div class="header">Calipso</div><div class="meta">Night Club</div><div class="description">this is a local night club .....</div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div>
          <div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/steve.jpg" class="ui mini right floated image"/><div class="header">Spur Tree</div><div class="meta">Friends who have been there</div><div class="description">Hottest restaurant in town <strong>best friends</strong></div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div><div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/molly.png" class="ui mini right floated image"/><div class="header">Untamed</div><div class="meta">Friends have been there</div><div class="description">This is a great spot for night life <strong>musicians</strong></div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div><div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/jenny.jpg" class="ui mini right floated image"/><div class="header">Calipso</div><div class="meta">Night Club</div><div class="description">this is a local night club .....</div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div>
          <div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/steve.jpg" class="ui mini right floated image"/><div class="header">Spur Tree</div><div class="meta">Friends who have been there</div><div class="description">Hottest restaurant in town <strong>best friends</strong></div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div><div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/molly.png" class="ui mini right floated image"/><div class="header">Untamed</div><div class="meta">Friends have been there</div><div class="description">This is a great spot for night life <strong>musicians</strong></div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div><div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/jenny.jpg" class="ui mini right floated image"/><div class="header">Calipso</div><div class="meta">Night Club</div><div class="description">this is a local night club .....</div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div>
          <div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/steve.jpg" class="ui mini right floated image"/><div class="header">Spur Tree</div><div class="meta">Friends who have been there</div><div class="description">Hottest restaurant in town <strong>best friends</strong></div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div><div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/molly.png" class="ui mini right floated image"/><div class="header">Untamed</div><div class="meta">Friends have been there</div><div class="description">This is a great spot for night life <strong>musicians</strong></div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div><div class="ui card"><div class="content"><img src="https://react.semantic-ui.com/images/avatar/large/jenny.jpg" class="ui mini right floated image"/><div class="header">Calipso</div><div class="meta">Night Club</div><div class="description">this is a local night club .....</div></div><div class="extra content"><div class="ui two buttons"><button class="ui green basic button">View map</button><button class="ui red basic button">share</button></div></div></div>
      </div>

    )
  }
}
